/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sequality;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.print("Sum of 2 and 3 is " + new Calculate().sum(2, 3) + ". ");
        System.out.println("Average is " + new Calculate().average(5, 2) + ". ");
        System.out.print("sum of 1 to 10 is " + new Calculate().sumall(1, 10) + ". ");
        System.out.println("Average is " + new Calculate().average(55, 10));
        System.out.print("Sum of odd of 1 to 10 is " + new Calculate().sumodd(1,10) + ". ");
        System.out.println("Sum of even is " + new Calculate().sumeven(1, 10) + ". ");
    }
}
