/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sequality;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println(new App().getSum(2, 3) + new App().getAve(2,3));
        System.out.println(new App().getSumall(1, 10) + new App().getAve(1,10));
        System.out.println(new App().getSumodd(1, 10) + new App().getSumeven(1,10));
    }

    public String getSum(int x, int y){
        return "Sum of " + x + " and " + y + " is " + new Calculate().sum(x,y) + ". ";
    }

    public String getAve(int x, int y){
        return "Average is " + new Calculate().average(x,y) + ". ";
    }

    public String getSumall(int x, int y){
        return "Sum of " + x + " to " + y + " is " + new Calculate().sumall(x,y) + ". ";
    }
    
    public String getSumodd(int x, int y){
        return "Sum of odd of " + x + " to " + y + " is " + new Calculate().sumodd(x,y) + ". ";
    }

    public String getSumeven(int x, int y){
        return "Sum of even is " + new Calculate().sumeven(x,y) + ". "; 
    }
}
